//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MFCApplication1.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROPPAGE_CUSERINFO          107
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MFCApplication1TYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_CATALOG               173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_CASE_VIEW                   307
#define ID_VIEW_CASEVIEW                308
#define IDD_CCTRLVIEW                   310
#define IDR_MENU1                       311
#define IDR_POPUP_CASE                  311
#define IDD_CONTENTVIEW                 312
#define IDD_PROPPAGE_CUSERSPROM         314
#define IDD_PROPPAGE_CUSERGROUP         315
#define IDD_PROPPAGE_RELAANDCELL        316
#define IDD_INPUTEDIT                   321
#define IDD_EXECSHELL_DIALOG            325
#define IDD_ContentDlg1                 327
#define IDD_ContentDlg2                 329
#define IDC_PREDATA                     1000
#define IDC_CLEANENV                    1002
#define IDC_CLEANDATA                   1002
#define IDC_COMPAREFILE                 1003
#define IDC_INPUTEDIT                   1004
#define IDC_COMPAREDATA                 1007
#define IDC_EDIT_USERSTATUS             1011
#define IDC_DATETIMEPICKER1             1012
#define IDC_DATETIMEPICKER2             1013
#define IDC_DATETIMEPICKER3             1014
#define IDC_DATETIMEPICKER4             1015
#define IDC_DATETIMEPICKER29            1016
#define IDC_DATETIMEPICKER30            1017
#define IDC_EDIT1                       1018
#define IDC_EDIT2                       1019
#define IDC_EDIT3                       1020
#define IDC_EDIT4                       1021
#define IDC_EDIT5                       1022
#define IDC_DATETIMEPICKER36            1022
#define IDC_EDIT6                       1023
#define IDC_DATETIMEPICKER37            1023
#define IDC_DATETIMEPICKER38            1024
#define IDC_EDIT_USERCYCLE              1024
#define IDC_EDIT8                       1025
#define IDC_DATETIMEPICKER39            1025
#define IDC_EDIT7                       1025
#define IDC_DATETIMEPICKER5             1026
#define IDC_EDIT_MGNTSTS                1026
#define IDC_DATETIMEPICKER6             1027
#define IDC_EDIT_ACCTSTS                1027
#define IDC_DATETIMEPICKER7             1028
#define IDC_EDIT_CYCLEPROPERTY          1028
#define IDC_DATETIMEPICKER8             1029
#define IDC_EDIT_CYCLETYPE              1029
#define IDC_DATETIMEPICKER34            1030
#define IDC_EDIT_CYCLELENGTH            1030
#define IDC_DATETIMEPICKER35            1031
#define IDC_EDIT_OPERSTS                1031
#define IDC_EDIT9                       1031
#define IDC_EDIT_CYCLEENDDAY            1032
#define IDC_BUTTON3                     1034
#define IDC_DATETIMEPICKER10            1035
#define IDC_BUTTON5                     1035
#define IDC_DATE_CYCLEEXPIRE            1035
#define IDC_DATETIMEPICKER11            1036
#define IDC_LIST1                       1036
#define IDC_TIME_CYCLEEXPIRE            1036
#define IDC_DATETIMEPICKER12            1037
#define IDC_LIST2                       1037
#define IDC_DATE_BILLCYCLEVALID         1037
#define IDC_DATETIMEPICKER31            1038
#define IDC_BUTTON4                     1038
#define IDC_LIST3                       1038
#define IDC_TIME_BILLCYCLEVALID         1038
#define IDC_DATETIMEPICKER32            1039
#define IDC_DATE_BILLCYCLEEXPIRE        1039
#define IDC_DATETIMEPICKER33            1040
#define IDC_TIME_BILLCYCLEEXPIRE        1040
#define IDC_EDIT_ACCTID                 1041
#define IDC_EDIT_SERVID                 1042
#define IDC_EDIT_CUSTID                 1043
#define IDC_EDIT_REGIONCODE             1044
#define IDC_EDIT_IMSI                   1045
#define IDC_EDIT_MSISDN                 1046
#define IDC_EDIT_USERSTS                1047
#define IDC_GRIDCTRL                    1049
#define IDC_COMPAREGRID                 1053
#define IDC_RICHEDIT22                  1061
#define IDC_CHECK1                      1062
#define IDC_CHECK2                      1063
#define IDC_COMBO1                      1064
#define IDC_COMBO2                      1065
#define IDC_RICHEDIT21                  1066
#define IDC_DATE_USERVALID              1069
#define IDC_TIME_USERVALID              1070
#define IDC_DATE_USEREXPIRE             1071
#define IDC_TIME_USEREXPIRE             1072
#define IDC_DATE_CYCLEVALID             1073
#define IDC_TIME_CYCLEVALID             1074
#define IDC_USER_DEFINE                 1100
#define IDC_EXECSHELL                   10010
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_OPEN_CASE                    32778
#define ID_NEW_CASE                     32779
#define ID_NEWCATALOG                   32780
#define ID_COPYCASE                     32781
#define ID_CPYCASETOLOCAL               32782
#define ID_CUTCASE                      32783
#define ID_PASTECASE                    32784
#define ID_DELETECASE                   32785
#define ID_EXPORTCASE                   32786
#define ID_REFRESHTREE                  32787
#define ID_CASEATTRIBUTE                32788
#define ID_Menu                         32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_RENAME                       32795
#define ID_32796                        32796
#define ID_DELETE                       32797
#define ID_EXPORT                       32798
#define ID_EXEC                         32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
